name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: check philo_mutexes
    
      run: make -C philo_mutexes

    - name: check philo_semaphores
    
      run: make -C philo_semaphores

  norminette:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: alexandregv/norminette-action@v3
